mkdir: cannot create directory ‘/scratch/cwagen-gaussian’: File exists
cp: cannot create regular file ‘/scratch/cwagen-gaussian/run_gaussian.sh’: File exists
mkdir: cannot create directory ‘/scratch/cwagen-xtb’: File exists
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-13:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-16:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-46:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-49:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-52:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-73:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-79:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-82:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-88:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-97:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-109:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-112:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-115:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-118:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-121:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-124:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-136:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-139:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-142:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-145:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-148:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-151:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-154:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-190:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-199:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-202:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-205:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-208:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-211:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-214:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-217:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-220:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-247:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-250:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-253:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-262:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-265:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-268:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-271:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-274:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-277:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-280:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-283:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-286:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-289:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-292:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-295:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-298:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-301:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-304:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-307:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-310:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-313:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-316:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-319:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-322:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-325:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-328:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-331:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-334:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-337:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-340:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-343:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-346:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-349:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-352:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-355:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-358:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-361:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-364:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-367:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-370:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-373:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-376:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-382:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-385:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-388:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-391:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-394:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-397:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-400:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-403:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-406:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-409:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-412:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-415:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-418:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-421:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-424:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-427:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-430:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-433:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-436:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-439:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-442:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-445:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-448:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-451:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-454:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-457:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-460:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-463:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-466:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-469:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-472:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-475:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-478:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-481:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-484:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-490:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-493:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-496:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-499:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-502:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-505:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-508:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-511:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-514:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-517:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-520:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-523:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-526:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-529:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-532:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-535:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-538:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-541:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-544:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-547:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-550:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-553:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-556:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-559:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-562:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-565:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-568:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-571:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-574:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-577:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-580:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-583:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-586:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-595:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-598:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-601:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-604:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-607:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-610:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-613:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-616:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-619:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-622:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-625:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-628:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-631:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-634:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-637:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-640:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-643:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-646:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-649:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-652:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-655:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-658:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-661:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-667:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-670:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-673:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-676:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-679:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-682:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-688:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-691:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-694:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-697:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-700:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-703:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-706:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-709:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-712:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-715:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-718:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-721:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-724:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-727:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-730:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-733:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-736:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-739:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-742:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-745:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-751:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
slurmstepd: error: *** JOB 11896788 ON holy7c21312 CANCELLED AT 2021-01-04T09:12:50 DUE TO PREEMPTION ***
