mkdir: cannot create directory ‘/scratch/cwagen-gaussian’: File exists
mkdir: cannot create directory ‘/scratch/cwagen-xtb’: File exists
fname=/scratch/Gau-18787.rwf fd = -1

open-new-file: Permission denied
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-1909:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
PGFIO/stdio: Invalid argument
PGFIO-F-/formatted write/unit=11/error code returned by host stdio - 22.
 File name = /scratch/Gau-11404.inp    formatted, sequential access   record = 0
 In source file ml0.f, at line number 213
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-2977:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
fname=/scratch/Gau-18787.rwf fd = -1

open-new-file: Permission denied
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-9226:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
fname=/scratch/Gau-15924.rwf fd = -1

open-new-file: Permission denied
warning: initial DIIS convergence failed, trying quadradic convergence
Process Process-10288:
Traceback (most recent call last):
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/presto/calculators.py", line 378, in evaluate
    energy += e
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
